from enum import Enum, auto

class Anchor(Enum):
    c = auto()
    e0 = auto()
    e1 = auto()
    e2 = auto()
    e3 = auto()
    e4 = auto()
    e5 = auto()
    e6 = auto()
    e7 = auto()
    e8 = auto()
    e9 = auto()
    e10 = auto()
    e11 = auto()
    f0 = auto()
    f1 = auto()
    f2 = auto()
    f3 = auto()
    f4 = auto()
    f5 = auto()
    v0 = auto()
    v1 = auto()
    v2 = auto()
    v3 = auto()
    v4 = auto()
    v5 = auto()
    v6 = auto()
    v7 = auto()
    v8 = auto()
